#!/bin/bash
cd ..
pyinstaller --onefile autovid/uploader.py
pyinstaller --onefile autovid/downloader.py
rm -r build
rm uploader.spec
rm downloader.spec
mv -f dist/uploader uploader
mv -f dist/downloader downloader
rm -r dist
echo "new versions built..."
