#!/bin/bash
cd ..
pyinstaller --onefile autovid/uploader.py
pyinstaller --onefile autovid/clipper.py
rm -r build
rm uploader.spec
rm clipper.spec
mv -f dist/uploader uploader
mv -f dist/clipper clipper
rm -r dist
echo "new versions built..."
